from effayoh.rectification.political_entities import FAOPolitEnt
from effayoh.mungers.psd import PSDCountry

# The mapping of political entities defined in the USDA database to
# their FAOPolitEnt counterpart.
#
# Some of the USDA country codes appear more than once in a PSDCountry
# because the USDA standard may give a different description than the
# one in the data sheet.
map = {
    PSDCountry("--", "Other"): FAOPolitEnt.OTHER,
    PSDCountry("AA", "Aruba"): FAOPolitEnt.ARUBA,
    PSDCountry("AC", "Antigua and Barbuda"): FAOPolitEnt.ANTIGUA_AND_BARBUDA,
    PSDCountry("AF", "Afghanistan"): FAOPolitEnt.AFGHANISTAN,
    PSDCountry("AG", "Algeria"): FAOPolitEnt.ALGERIA,
    PSDCountry("AJ", "Azerbaijan, Republic of"): FAOPolitEnt.AZERBAIJAN,
    PSDCountry("AJ", "Azerbaijan"): FAOPolitEnt.AZERBAIJAN,
    PSDCountry("AL", "Albania"): FAOPolitEnt.ALBANIA,
    PSDCountry("AM", "Armenia, Republic of"): FAOPolitEnt.ARMENIA,
    PSDCountry("AM", "Armenia"): FAOPolitEnt.ARMENIA,
    PSDCountry("AO", "Angola"): FAOPolitEnt.ANGOLA,
    PSDCountry("AR", "Argentina"): FAOPolitEnt.ARGENTINA,
    PSDCountry("AS", "Australia"): FAOPolitEnt.AUSTRALIA,
    PSDCountry("AU", "Austria"): FAOPolitEnt.AUSTRIA,
    PSDCountry("AV", "Anguilla"): FAOPolitEnt.ANGUILLA,
    PSDCountry("BA", "Bahrain"): FAOPolitEnt.BAHRAIN,
    PSDCountry("BB", "Barbados"): FAOPolitEnt.BARBADOS,
    PSDCountry("BC", "Botswana"): FAOPolitEnt.BOTSWANA,
    PSDCountry("BD", "Bermuda"): FAOPolitEnt.BERMUDA,
    PSDCountry("BE", "Belgium-Luxembourg"): FAOPolitEnt.BELGIUM_LUXEMBOURG,
    PSDCountry("BF", "Bahamas, The"): FAOPolitEnt.BAHAMAS,
    PSDCountry("BG", "Bangladesh"): FAOPolitEnt.BANGLADESH,
    PSDCountry("BH", "Belize"): FAOPolitEnt.BELIZE,
    PSDCountry("BK", "Bosnia-Hercegovina"): FAOPolitEnt.BOSNIA_AND_HERZEGOVINA,
    PSDCountry("BK", "Bosnia and Herzegovina"): FAOPolitEnt.BOSNIA_AND_HERZEGOVINA,
    PSDCountry("BL", "Bolivia"): FAOPolitEnt.BOLIVIA,
    PSDCountry("BM", "Burma"): FAOPolitEnt.MYANMAR,
    PSDCountry("BO", "Belarus"): FAOPolitEnt.BELARUS,
    PSDCountry("BP", "Solomon Islands"): FAOPolitEnt.SOLOMON_ISLANDS,
    PSDCountry("BR", "Brazil"): FAOPolitEnt.BRAZIL,
    PSDCountry("BT", "Bhutan"): FAOPolitEnt.BHUTAN,
    PSDCountry("BU", "Bulgaria"): FAOPolitEnt.BULGARIA,
    PSDCountry("BX", "Brunei"): FAOPolitEnt.BRUNEI_DARUSSALAM,
    PSDCountry("BY", "Burundi"): FAOPolitEnt.BURUNDI,
    PSDCountry("CA", "Canada"): FAOPolitEnt.CANADA,
    PSDCountry("CB", "Cambodia"): FAOPolitEnt.CAMBODIA,
    PSDCountry("CD", "Chad"): FAOPolitEnt.CHAD,
    PSDCountry("CE", "Sri Lanka"): FAOPolitEnt.SRI_LANKA,
    PSDCountry("CF", "Congo (Brazzaville)"): FAOPolitEnt.CONGO,
    PSDCountry("CG", "Congo, Democratic Rep of the"): FAOPolitEnt.CONGO_DR,
    PSDCountry("CG", "Congo (Kinshasa)"): FAOPolitEnt.CONGO_DR,
    PSDCountry("CH", "China, Peoples Republic of"): FAOPolitEnt.CHINA,
    PSDCountry("CH", "China"): FAOPolitEnt.CHINA,
    PSDCountry("CI", "Chile"): FAOPolitEnt.CHILE,
    PSDCountry("CJ", "Cayman Islands"): FAOPolitEnt.CAYMAN_ISLANDS,
    PSDCountry("CM", "Cameroon"): FAOPolitEnt.CAMEROON,
    PSDCountry("CN", "Comoros"): FAOPolitEnt.COMOROS,
    PSDCountry("CO", "Colombia"): FAOPolitEnt.COLOMBIA,
    PSDCountry("CS", "Costa Rica"): FAOPolitEnt.COSTA_RICA,
    PSDCountry("CT", "Central African Republic"): FAOPolitEnt.CENTRAL_AFRICAN_REPUBLIC,
    PSDCountry("CU", "Cuba"): FAOPolitEnt.CUBA,
    PSDCountry("CV", "Cape Verde"): FAOPolitEnt.CABO_VERDE,
    PSDCountry("CY", "Cyprus"): FAOPolitEnt.CYPRUS,
    PSDCountry("CZ", "Czechoslovakia"): FAOPolitEnt.CZECHOSLOVAKIA,
    PSDCountry("DA", "Denmark"): FAOPolitEnt.DENMARK,
    PSDCountry("DJ", "Djibouti Afars-Issas"): FAOPolitEnt.DJIBOUTI,
    PSDCountry("DJ", "Djibouti"): FAOPolitEnt.DJIBOUTI,
    PSDCountry("DM", "Benin"): FAOPolitEnt.BENIN,
    PSDCountry("DO", "Dominica"): FAOPolitEnt.DOMINICA,
    PSDCountry("DR", "Dominican Republic"): FAOPolitEnt.DOMINICAN_REPUBLIC,
    PSDCountry("E2", "EU-15"): FAOPolitEnt.EU_15,
    PSDCountry("E3", "EU-25"): FAOPolitEnt.EU_25,
    PSDCountry("E4", "European Union"): FAOPolitEnt.EU,
    PSDCountry("EC", "Ecuador"): FAOPolitEnt.ECUADOR,
    PSDCountry("EG", "Egypt"): FAOPolitEnt.EGYPT,
    PSDCountry("EI", "Ireland"): FAOPolitEnt.IRELAND,
    PSDCountry("EK", "Equatorial Guinea"): FAOPolitEnt.EQUATORIAL_GUINEA,
    PSDCountry("EN", "Estonia"): FAOPolitEnt.ESTONIA,
    PSDCountry("ER", "Eritrea"): FAOPolitEnt.ERITREA,
    PSDCountry("ES", "El Salvador"): FAOPolitEnt.EL_SALVADOR,
    PSDCountry("ET", "Ethiopia"): FAOPolitEnt.ETHIOPIA,
    PSDCountry("EZ", "Czech Republic"): FAOPolitEnt.CZECHIA,
    PSDCountry("FA", "Falkland Islands (Islas Malvin"): FAOPolitEnt.FALKLAND_ISLANDS,
    PSDCountry("FG", "French Guiana"): FAOPolitEnt.FRENCH_GUIANA,
    PSDCountry("FI", "Finland"): FAOPolitEnt.FINLAND,
    PSDCountry("FJ", "Fiji"): FAOPolitEnt.FIJI,
    PSDCountry("FO", "Faroe Islands"): FAOPolitEnt.FAROE_ISLANDS,
    PSDCountry("FP", "French Polynesia"): FAOPolitEnt.FRENCH_POLYNESIA,
    PSDCountry("FR", "France"): FAOPolitEnt.FRANCE,
    PSDCountry("FT", "Fr.Ter.Africa-Issas"): FAOPolitEnt.FTAI,
    PSDCountry("GA", "Gambia, The"): FAOPolitEnt.GAMBIA,
    PSDCountry("GB", "Gabon"): FAOPolitEnt.GABON,
    PSDCountry("GC", "German Democratic Republic"): FAOPolitEnt.EAST_GERMANY,
    PSDCountry("GE", "Germany, Federal Rebpulic of"): FAOPolitEnt.WEST_GERMANY,
    PSDCountry("GG", "Georgia, Republic of"): FAOPolitEnt.GEORGIA,
    PSDCountry("GG", "Georgia"): FAOPolitEnt.GEORGIA,
    PSDCountry("GH", "Ghana"): FAOPolitEnt.GHANA,
    PSDCountry("GI", "Gibraltar"): FAOPolitEnt.GIBRALTAR,
    PSDCountry("GJ", "Grenada"): FAOPolitEnt.GRENADA,
    PSDCountry("GL", "Greenland"): FAOPolitEnt.GREENLAND,
    PSDCountry("GM", "Germany"): FAOPolitEnt.GERMANY,
    PSDCountry("GP", "Guadeloupe"): FAOPolitEnt.GUADELOUPE,
    PSDCountry("GQ", "Guam"): FAOPolitEnt.GUAM,
    PSDCountry("GR", "Greece"): FAOPolitEnt.GREECE,
    PSDCountry("GT", "Guatemala"): FAOPolitEnt.GUATEMALA,
    PSDCountry("GU", "Guinea"): FAOPolitEnt.GUINEA,
    PSDCountry("GY", "Guyana"): FAOPolitEnt.GUYANA,
    PSDCountry("HA", "Haiti"): FAOPolitEnt.HAITI,
    PSDCountry("HK", "Hong Kong"): FAOPolitEnt.CHINA_HK_SAR,
    PSDCountry("HO", "Honduras"): FAOPolitEnt.HONDURAS,
    PSDCountry("HR", "Croatia"): FAOPolitEnt.CROATIA,
    PSDCountry("HU", "Hungary"): FAOPolitEnt.HUNGARY,
    PSDCountry("IC", "Iceland"): FAOPolitEnt.ICELAND,
    PSDCountry("ID", "Indonesia"): FAOPolitEnt.INDONESIA,
    PSDCountry("IN", "India"): FAOPolitEnt.INDIA,
    PSDCountry("IR", "Iran"): FAOPolitEnt.IRAN,
    PSDCountry("IS", "Israel"): FAOPolitEnt.ISRAEL,
    PSDCountry("IT", "Italy"): FAOPolitEnt.ITALY,
    PSDCountry("IV", "Cote d'Ivoire"): FAOPolitEnt.COTE_DIVOIRE,
    PSDCountry("IZ", "Iraq"): FAOPolitEnt.IRAQ,
    PSDCountry("JA", "Japan"): FAOPolitEnt.JAPAN,
    PSDCountry("JM", "Jamaica and Dep"): FAOPolitEnt.JAMAICA,
    PSDCountry("JM", "Jamaica"): FAOPolitEnt.JAMAICA,
    PSDCountry("JO", "Jordan"): FAOPolitEnt.JORDAN,
    PSDCountry("KE", "Kenya"): FAOPolitEnt.KENYA,
    PSDCountry("KG", "Kyrgyzstan, Republic of"): FAOPolitEnt.KYRGYZSTAN,
    PSDCountry("KG", "Kyrgyzstan"): FAOPolitEnt.KYRGYZSTAN,
    PSDCountry("KN", "Korea, Democratic Peoples Rep"): FAOPolitEnt.NORTH_KOREA,
    PSDCountry("KN", "Korea, North"): FAOPolitEnt.NORTH_KOREA,
    PSDCountry("KS", "Korea, Republic of"): FAOPolitEnt.SOUTH_KOREA,
    PSDCountry("KS", "Korea, South"): FAOPolitEnt.SOUTH_KOREA,
    PSDCountry("KU", "Kuwait"): FAOPolitEnt.KUWAIT,
    PSDCountry("KZ", "Kazakhstan, Republic of"): FAOPolitEnt.KAZAKHSTAN,
    PSDCountry("KZ", "Kazakhstan"): FAOPolitEnt.KAZAKHSTAN,
    PSDCountry("LA", "Laos"): FAOPolitEnt.LAOS,
    PSDCountry("LE", "Lebanon"): FAOPolitEnt.LEBANON,
    PSDCountry("LG", "Latvia"): FAOPolitEnt.LATVIA,
    PSDCountry("LH", "Lithuania"): FAOPolitEnt.LITHUANIA,
    PSDCountry("LI", "Liberia"): FAOPolitEnt.LIBERIA,
    PSDCountry("LO", "Slovakia"): FAOPolitEnt.SLOVAKIA,
    PSDCountry("LT", "Lesotho"): FAOPolitEnt.LESOTHO,
    PSDCountry("LU", "Luxembourg"): FAOPolitEnt.LUXEMBOURG,
    PSDCountry("LY", "Libya"): FAOPolitEnt.LIBYA,
    PSDCountry("MA", "Madagascar"): FAOPolitEnt.MADAGASCAR,
    PSDCountry("MC", "Macau"): FAOPolitEnt.CHINA_MACAO_SAR,
    PSDCountry("MD", "Moldova, Republic of"): FAOPolitEnt.MOLDOVA,
    PSDCountry("MD", "Moldova"): FAOPolitEnt.MOLDOVA,
    PSDCountry("MG", "Mongolia"): FAOPolitEnt.MONGOLIA,
    PSDCountry("MI", "Malawi"): FAOPolitEnt.MALAWI,
    PSDCountry("MK", "Macedonia (Skopje)"): FAOPolitEnt.MACEDONIA,
    PSDCountry("MK", "Macedonia"): FAOPolitEnt.MACEDONIA,
    PSDCountry("ML", "Mali"): FAOPolitEnt.MALI,
    PSDCountry("MO", "Morocco"): FAOPolitEnt.MOROCCO,
    PSDCountry("MP", "Mauritius"): FAOPolitEnt.MAURITIUS,
    PSDCountry("MR", "Mauritania"): FAOPolitEnt.MAURITANIA,
    PSDCountry("MT", "Malta"): FAOPolitEnt.MALTA,
    PSDCountry("MU", "Oman"): FAOPolitEnt.OMAN,
    PSDCountry("MX", "Mexico"): FAOPolitEnt.MEXICO,
    PSDCountry("MY", "Malaysia"): FAOPolitEnt.MALAYSIA,
    PSDCountry("MZ", "Mozambique"): FAOPolitEnt.MOZAMBIQUE,
    PSDCountry("NG", "Niger"): FAOPolitEnt.NIGER,
    PSDCountry("NI", "Nigeria"): FAOPolitEnt.NIGERIA,
    PSDCountry("NL", "Netherlands"): FAOPolitEnt.NETHERLANDS,
    PSDCountry("NO", "Norway"): FAOPolitEnt.NORWAY,
    PSDCountry("NP", "Nepal"): FAOPolitEnt.NEPAL,
    PSDCountry("NS", "Surinam"): FAOPolitEnt.SURINAME,
    PSDCountry("NS", "Suriname"): FAOPolitEnt.SURINAME,
    PSDCountry("NU", "Nicaragua"): FAOPolitEnt.NICARAGUA,
    PSDCountry("NZ", "New Zealand"): FAOPolitEnt.NEW_ZEALAND,
    PSDCountry("OD", "South Sudan"): FAOPolitEnt.SOUTH_SUDAN,
    PSDCountry("PA", "Paraguay"): FAOPolitEnt.PARAGUAY,
    PSDCountry("PE", "Peru"): FAOPolitEnt.PERU,
    PSDCountry("PK", "Pakistan"): FAOPolitEnt.PAKISTAN,
    PSDCountry("PL", "Poland"): FAOPolitEnt.POLAND,
    PSDCountry("PN", "Panama"): FAOPolitEnt.PANAMA,
    PSDCountry("PO", "Portugal"): FAOPolitEnt.PORTUGAL,
    PSDCountry("PP", "Papua New Guinea"): FAOPolitEnt.PAPUA_NEW_GUINEA,
    PSDCountry("PU", "Guinea-Bissau"): FAOPolitEnt.GUINEA_BISSAU,
    PSDCountry("QA", "Qatar"): FAOPolitEnt.QATAR,
    PSDCountry("RB", "Serbia"): FAOPolitEnt.SERBIA,
    PSDCountry("RE", "Reunion"): FAOPolitEnt.REUNION,
    PSDCountry("RH", "Zimbabwe"): FAOPolitEnt.ZIMBABWE,
    PSDCountry("RO", "Romania"): FAOPolitEnt.ROMANIA,
    PSDCountry("RP", "Philippines"): FAOPolitEnt.PHILIPPINES,
    PSDCountry("RQ", "Puerto Rico"): FAOPolitEnt.PUERTO_RICO,
    PSDCountry("RS", "Russian Federation"): FAOPolitEnt.RUSSIA,
    PSDCountry("RS", "Russia"): FAOPolitEnt.RUSSIA,
    PSDCountry("RW", "Rwanda"): FAOPolitEnt.RWANDA,
    PSDCountry("S8", "Belgium (without Luxembourg)"): FAOPolitEnt.BELGIUM,
    PSDCountry("SA", "Saudi Arabia"): FAOPolitEnt.SAUDI_ARABIA,
    PSDCountry("SF", "South Africa, Republic of"): FAOPolitEnt.SOUTH_AFRICA,
    PSDCountry("SF", "South Africa"): FAOPolitEnt.SOUTH_AFRICA,
    PSDCountry("SG", "Senegal"): FAOPolitEnt.SENEGAL,
    PSDCountry("SI", "Slovenia"): FAOPolitEnt.SLOVENIA,
    PSDCountry("SL", "Sierra Leone"): FAOPolitEnt.SIERRA_LEONE,
    PSDCountry("SN", "Singapore"): FAOPolitEnt.SINGAPORE,
    PSDCountry("SO", "Somalia"): FAOPolitEnt.SOMALIA,
    PSDCountry("SP", "Spain"): FAOPolitEnt.SPAIN,
    PSDCountry("SR", "Serbia and Montenegro"): FAOPolitEnt.SERBIA_AND_MONTENEGRO,
    PSDCountry("SU", "Sudan"): FAOPolitEnt.SUDAN,
    PSDCountry("SW", "Sweden"): FAOPolitEnt.SWEDEN,
    PSDCountry("SY", "Syria"): FAOPolitEnt.SYRIA,
    PSDCountry("SZ", "Switzerland"): FAOPolitEnt.SWITZERLAND,
    PSDCountry("T4", "French Equatorial Africa"): FAOPolitEnt.FRENCH_EQUATORIAL_AFRICA,
    PSDCountry("TC", "United Arab Emirates"): FAOPolitEnt.UNITED_ARAB_EMIRATES,
    PSDCountry("TD", "Trinidad and Tobago"): FAOPolitEnt.TRINIDAD_AND_TOBAGO,
    PSDCountry("TH", "Thailand"): FAOPolitEnt.THAILAND,
    PSDCountry("TI", "Tajikistan, Republic of"): FAOPolitEnt.TAJIKISTAN,
    PSDCountry("TI", "Tajikistan"): FAOPolitEnt.TAJIKISTAN,
    PSDCountry("TO", "Togo"): FAOPolitEnt.TOGO,
    PSDCountry("TS", "Tunisia"): FAOPolitEnt.TUNISIA,
    PSDCountry("TU", "Turkey"): FAOPolitEnt.TURKEY,
    PSDCountry("TW", "Taiwan"): FAOPolitEnt.CHINA_TAIWAN,
    PSDCountry("TX", "Turkmenistan"): FAOPolitEnt.TURKMENISTAN,
    PSDCountry("TZ", "Tanzania, United Republic of"): FAOPolitEnt.TANZANIA,
    PSDCountry("TZ", "Tanzania"): FAOPolitEnt.TANZANIA,
    PSDCountry("UG", "Uganda"): FAOPolitEnt.UGANDA,
    PSDCountry("UK", "United Kingdom"): FAOPolitEnt.UNITED_KINGDOM,
    PSDCountry("UP", "Ukraine"): FAOPolitEnt.UKRAINE,
    PSDCountry("UR", "Union of Soviet Socialist Repu"): FAOPolitEnt.USSR,
    PSDCountry("US", "United States"): FAOPolitEnt.USA,
    PSDCountry("UV", "Burkina"): FAOPolitEnt.BURKINA_FASO,
    PSDCountry("UY", "Uruguay"): FAOPolitEnt.URUGUAY,
    PSDCountry("UZ", "Uzbekistan, Republic of"): FAOPolitEnt.UZBEKISTAN,
    PSDCountry("UZ", "Uzbekistan"): FAOPolitEnt.UZBEKISTAN,
    PSDCountry("V1", "Vietnam, North"): FAOPolitEnt.NORTH_VIETNAM,
    PSDCountry("V2", "Vietnam, Republic of (South)"): FAOPolitEnt.SOUTH_VIETNAM,
    PSDCountry("VE", "Venezuela"): FAOPolitEnt.VENEZUELA,
    PSDCountry("VM", "Vietnam"): FAOPolitEnt.VIETNAM,
    PSDCountry("WA", "Namibia"): FAOPolitEnt.NAMIBIA,
    PSDCountry("WI", "Western Sahara"): FAOPolitEnt.WESTERN_SAHARA,
    PSDCountry("WZ", "Swaziland"): FAOPolitEnt.SWAZILAND,
    PSDCountry("YE", "Yemen (Sanaa)"): FAOPolitEnt.NORTH_YEMEN,
    PSDCountry("YI", "Yugoslavia (>01/2001)"): FAOPolitEnt.YUGOSLAVIA_GT_01,
    PSDCountry("YM", "Yemen"): FAOPolitEnt.YEMEN,
    PSDCountry("YO", "Yugoslavia"): FAOPolitEnt.YUGOSLAVIA,
    PSDCountry("YS", "Yemen (Aden)"): FAOPolitEnt.SOUTH_YEMEN,
    PSDCountry("YU", "Yugoslavia (>05/92)"): FAOPolitEnt.YUGOSLAVIA_GT_92,
    PSDCountry("Z5", "Ryukyu Islands/Nansei Islands"): FAOPolitEnt.RYUKYU,
    PSDCountry("ZA", "Zambia"): FAOPolitEnt.ZAMBIA
}
